### PR TITLE
Fixed URI parsing #207

### LINKED ISSUE #207: Error when header parsing
When request target is origin-form and contain right absolute path, like this:
`GET /somepath?param=http://example.com HTTP/1.1`

`RequestHeaderParser` throw `InvalidArgumentException('Invalid absolute-form request-target')`

This error can be corrected by changing the test condition, for example
```
((!isset($parts['scheme'], $parts['host']) || $parts['scheme'] !== 'http' || isset($parts['fragment'])) && !isset($parts['path']))
```

### PR DESCRIPTION
**Pull request by aaronbonneau**
Closes #207

### CODE REVIEW

File: src/RequestHeaderParser.php [hunk 1]
```diff
@@ -158,7 +158,7 @@ private function parseRequest($headers)
             $parts = parse_url($request->getRequestTarget());
 
             // make sure value contains valid host component (IP or hostname), but no fragment
-            if (!isset($parts['scheme'], $parts['host']) || $parts['scheme'] !== 'http' || isset($parts['fragment'])) {
+            if ((!isset($parts['scheme'], $parts['host']) || $parts['scheme'] !== 'http' || isset($parts['fragment'])) && isset($parts['scheme'])) {
```
Comment (clue) [inline src/RequestHeaderParser.php]: This is now really hard to read and I'm not sure it does what it's supposed to do anymore. It looks like a `request-target` that starts with `://` will now pass this validation?

As an alternative, may I suggest reverting this and updating the above check instead? Your issue can only really happen for `origin-target` requests, which means we can actually skip this whole block if the `request-target` starts with a `/`.

Does this make sense to you?

Comment (aaronbonneau) [inline src/RequestHeaderParser.php]: Yes, this is very difficult to read; I'll update it.
